angular.module("config", [])
.constant("COSMIC_BUCKET", "dollfinder-app")
.constant("MEDIA_URL", "https://api.cosmicjs.com/v1/dollfinder-app/media")
.constant("URL", "https://api.cosmicjs.com/v1/")
.constant("READ_KEY", "aunWBeYPX4YRWNcRa92gHSwkZwJE7r4wxQbvjFpuvBTEAvYzkq")
.constant("WRITE_KEY", "yff8Us81i1Hloe4HS1QJfsyJaiaQ0AUg9OEZhJwEWbfjPq5sUz")
.constant("COSMIC_READ_KEY", "aunWBeYPX4YRWNcRa92gHSwkZwJE7r4wxQbvjFpuvBTEAvYzkq")
.constant("COSMIC_WRITE_KEY", "yff8Us81i1Hloe4HS1QJfsyJaiaQ0AUg9OEZhJwEWbfjPq5sUz")
.constant("STRIPE_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2thZWwuY2hlbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiaWF0IjoxNTYzODY0NDExfQ.-RCe5wqJRZZmL5fmowpy59T3M6JmgK3dy7fG4vLvv0g");
